language: php

php:
    - "5.5"
    - "5.4"
    - "5.3"

before_install:
    - composer selfupdate
    - sudo apt-get update
    - sudo apt-get install libssh2-1 libssh2-1-dev
    - pecl install ssh2 channel://pecl.php.net/ssh2-0.12
    - phpenv config-add php.ini

install: composer update --prefer-dist --no-interaction

script:
    - phpunit --coverage-text